//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by AppLines.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define ID_DRAWING_PERF                 101
#define IDR_MAINFRAME                   128
#define IDR_BLZ3TYPE                    129
#define IDR_TOOLBAR_VIEW                130
#define IDR_DISPLAYTYPE                 130
#define IDR_TOOLBAR_ACTION              132
#define IDR_TOOLBAR_OBJECT              134
#define IDD_NEBULAR                     134
#define IDD_DISTRIBUTED                 135
#define IDR_TOOLBAR_DISPLAY             137
#define IDC_PANNING                     137
#define IDD_SCENE                       138
#define IDD_SUPER_SAMPLE                139
#define IDD_MODELLER_INFO               140
#define IDD_HIERARCHY                   145
#define IDD_LENS_FLARE                  146
#define IDI_BBOX_WORLD                  148
#define IDI_BBOX_SUB                    149
#define IDI_BBOX_SHAPES                 150
#define IDI_BBOX_SHAPES_SUB             151
#define IDI_BBOX_S_SHAPES_SUB           152
#define IDI_BBOX_S_SHAPES               153
#define IDI_BBOX_EMPTY                  155
#define IDM_BAR_VIEW                    252
#define IDC_PREVIEW_RAYTRACE            1000
#define IDC_PREVIEW_BGIMAGE             1001
#define IDC_BG_LIGHT                    1002
#define IDC_BG_COLOR                    1003
#define IDC_BG_IMAGE                    1004
#define IDC_BG_SKY                      1005
#define IDC_RES_VALID                   1006
#define IDC_XRES                        1008
#define IDC_YRES                        1009
#define IDC_XRES_SPIN                   1010
#define IDC_ACT_NEBULAR                 1010
#define IDC_YRES_SPIN                   1011
#define IDC_SPP                         1011
#define IDC_RAYDEPTH                    1012
#define IDC_ACT_DISTRIBUTED             1012
#define IDC_RAYDEPTH_LEGEND             1013
#define IDC_TFLTR_BOX                   1013
#define IDC_BG_IMAGE_SELECT             1014
#define IDC_TFLTR_GAUSS                 1014
#define IDC_BG_TOP_SELECT               1015
#define IDC_TFLTR_SHUTTER               1015
#define IDC_BG_BOTTOM_SELECT            1016
#define IDC_ACT_MOTION_BLUR             1016
#define IDC_OPEN_GFX                    1017
#define IDC_SPF                         1017
#define IDC_SHADOW_BRIGHTNESS           1018
#define IDC_SMP_REGULAR                 1018
#define IDC_NEB_PREVIEW                 1018
#define IDC_SHADOW_BRIGHTNESS_LEGEND    1019
#define IDC_SMP_RANDOM                  1019
#define IDC_NEB_DISTANCE                1019
#define IDC_SMP_JITTER                  1020
#define IDC_LF_PREVIEW                  1020
#define IDC_SMP_SEMI                    1021
#define IDC_SS4_GREEN_LEGEND            1021
#define IDC_SMP_SEPARATED               1022
#define IDC_SS4_RED_LEGEND              1022
#define IDC_PFLTR_BOX                   1023
#define IDC_SS4_BLUE_LEGEND             1023
#define IDC_PFLTR_GAUSS                 1024
#define IDC_SPP_SPIN                    1026
#define IDC_SCAN_PARA                   1027
#define IDC_SPF_SPIN                    1028
#define IDC_SNAP_TO_GRID                1029
#define IDC_SNAP_TO_ANGLE               1030
#define IDC_STEP_GRID                   1031
#define IDC_STEP_ANGLE                  1032
#define IDC_FULCRUM_X                   1033
#define IDC_FULCRUM_Y                   1034
#define IDC_FULCRUM_Z                   1035
#define IDC_FULCRUM_CLR                 1036
#define IDC_ACT_LENS_FLARE              1039
#define IDC_LF_CHANGE                   1040
#define IDC_LF_COLOR                    1041
#define IDC_LF_VALUE                    1042
#define IDC_NEB_COLOR                   1043
#define ID_NEB_CHANGE                   1044
#define IDC_SS4_ACTIVE                  1046
#define IDC_SS4_RED                     1047
#define IDC_SS4_GREEN                   1048
#define IDC_SS4_BLUE                    1049
#define IDC_HIERARCHY                   1050
#define IDC_ACTIVATE                    1055
#define IDC_DEACTIVATE                  1056
#define IDC_ALL_ACTIVATE                1057
#define IDC_ALL_DEACTIVATE              1058
#define ID_PREF_SAVE                    30005
#define ID_PREF_AUTOSAVE                30006
#define ID_CUST_VIEW                    30026
#define ID_CUST_MAIN                    30029
#define ID_B3_ORIGINAL                  30041
#define ID_B3_WIDTH                     30042
#define ID_B3_HEIGHT                    30043
#define ID_B3_FULL                      30044
#define ID_B3_MORE                      30045
#define ID_B3_LESS                      30046
#define ID_B3_MAGNIFY                   30047
#define ID_B3_UNFILTERED                30048
#define ID_B3_FILTERED                  30049
#define ID_PAGE_SAVE                    31000
#define ID_VIEW_THUMB                   31014
#define ID_PAGE_SAVE_ALL                31015
#define ID_VIEW_PARAM_DEFINE            31029
#define ID_VIEW_PARAM_SET               31030
#define ID_VIEW_PARAM_DELETE            31031
#define ID_SHOW_RES                     31036
#define ID_FRONT                        32771
#define ID_VIEW_TOP                     32772
#define ID_VIEW_BACK                    32774
#define ID_VIEW_LEFT                    32775
#define ID_VIEW_PERSPECTIVE             32778
#define ID_VIEW_FRONT                   32779
#define ID_VIEW_RIGHT                   32780
#define ID_VIEW_ANTIALIAS               32781
#define ID_VIEW_BIGGER                  32782
#define ID_VIEW_SMALLER                 32783
#define ID_VIEW_SELECT                  32784
#define ID_VIEW_ORIGINAL                32787
#define ID_VIEW_MOVE_RIGHT              32788
#define ID_VIEW_MOVE_LEFT               -32747
#define ID_VIEW_MOVE_BOTTOM             -32746
#define ID_VIEW_MOVE_TOP                -32745
#define ID_VIEW_POP                     32792
#define ID_ACT_SELECT                   32793
#define ID_OBJ_MOVE                     32794
#define ID_OBJ_ROTATE                   32795
#define ID_OBJ_SCALE                    32796
#define ID_CAM_TURN                     32797
#define ID_CAM_ROTATE                   32798
#define ID_CAM_MOVE                     32799
#define ID_CAM_SELECT                   32800
#define ID_LIGHT_SELECT                 32801
#define ID_LIGHT_TURN                   32802
#define ID_CAM_VIEW                     32803
#define ID_CUST_ACTION                  32804
#define IDM_BAR_ACTION                  32805
#define ID_OBJ_SELECT                   32806
#define ID_HIERACHY                     32808
#define ID_RAYTRACE                     32809
#define ID_CUST_DISPLAY                 32810
#define IDM_BAR_DISPLAY                 32812
#define ID_DLG_SCENE                    32813
#define IDM_BAR_SCENE                   32814
#define ID_CUST_SCENE                   32815
#define ID_MODELLER_INFO                32816
#define ID_VIEW_TO_FULCRUM              32817
#define IDS_TEXTURE_FILTER              60013
#define IDS_TOOLBAR_MAINFRAME           61446
#define IDS_TOOLBAR_VIEW                61447
#define IDS_TOOLBAR_ACTION              61447
#define IDS_TOOLBAR_OBJECT              61448
#define IDS_TOOLBAR_DISPLAY             61449
#define IDS_FRAME_RATE                  61450
#define IDS_RAYTRACE_TITLE              61451
#define IDS_RAYDEPTH                    61452
#define IDS_SCENE_NEW                   61453
#define IDS_SHADOW_BRIGHTNESS           61454
#define IDS_TITLE_SCENE                 61455
#define IDS_SS4_RED_LEGEND              61456
#define IDS_SS4_GREEN_LEGEND            61457
#define IDS_SS4_BLUE_LEGEND             61458

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         32818
#define _APS_NEXT_CONTROL_VALUE         1037
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
