//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by AppLines.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             101
#define IDB_SPLASH                      102
#define IDS_ASK_DELETE_CAMERA           108
#define IDS_LIGHT_SAMPLE_LABEL          109
#define IDR_MAINFRAME                   110
#define IDR_BLZ3TYPE                    111
#define IDR_DISPLAYTYPE                 112
#define IDR_OBJECT                      113
#define IDR_TOOLBAR_VIEW                114
#define IDR_TOOLBAR_ACTION              115
#define IDR_TOOLBAR_OBJECT              116
#define IDR_TOOLBAR_DISPLAY             117
#define IDR_TOOLBAR_CAMERA              118
#define IDR_TOOLBAR_LIGHT               119
#define IDD_DISTRIBUTED                 120
#define IDC_PANNING                     121
#define IDD_SCENE                       122
#define IDD_SUPER_SAMPLE                123
#define IDD_MODELLER_INFO               124
#define IDD_HIERARCHY                   125
#define IDD_LENS_FLARE                  126
#define IDD_NEW_ITEM                    127
#define IDI_BBOX_WORLD                  128
#define IDD_LIGHT                       129
#define IDI_BBOX_SUB                    130
#define IDD_CAMERA                      131
#define IDI_BBOX_SHAPES                 132
#define IDI_BBOX_SHAPES_SUB             133
#define IDD_FULCRUM                     134
#define IDI_BBOX_S_SHAPES_SUB           135
#define IDI_BBOX_S_SHAPES               136
#define IDD_OBJECT_COPY                 137
#define IDD_ACTION                      138
#define IDI_BBOX_EMPTY                  139
#define IDI_LEFT                        140
#define IDI_RIGHT                       141
#define IDI_UP                          142
#define IDI_DOWN                        143
#define IDI_ROT_LEFT                    144
#define IDI_ROT_RIGHT                   145
#define IDM_BAR_VIEW                    146
#define IDD_SEARCH_PATH_LIST            147
#define IDD_LDC                         148
#define IDD_STEP_MOVE                   149
#define IDD_STEP_ROTATE                 150
#define IDD_FILEOPENPREVIEW             151
#define IDD_NEBULAR                     152
#define IDM_BAR_DISPLAY                 153
#define IDM_BAR_SCENE                   154
#define IDM_BAR_CAMERA                  155
#define IDM_BAR_LIGHT                   156
#define IDM_BAR_FULCRUM                 157
#define IDM_BAR_STEP_MOVE               158
#define IDM_BAR_STEP_ROTATE             159
#define IDR_CONTEXT_SCENE               166
#define IDI_SHAPE_CYLINDER              167
#define IDR_CONTEXT_OBJECT              167
#define IDI_SHAPE_SPHERE                168
#define IDI_SHAPE_CONE                  169
#define IDI_SHAPE_ELLIPSOID             170
#define IDI_SHAPE_AREA                  171
#define IDI_SHAPE_DISK                  172
#define IDD_PRINTDIALOG                 172
#define IDI_SHAPE_BOX                   173
#define IDI_SHAPE_TORUS                 174
#define IDD_PROPERTIES                  174
#define IDI_SHAPE_TRIANGLES             175
#define IDD_NEW_OBJECT                  175
#define IDI_SHAPE_BSPLINE_ROT           176
#define IDI_SHAPE_BSPLINE_AREA          177
#define IDI_SHAPE_BSPLINE_CYLINDER      178
#define IDI_SHAPE_BSPLINE_RING          179
#define IDI_CSG_TORUS                   180
#define IDI_CSG_BOX                     181
#define IDI_CSG_ELLIPSOID               182
#define IDI_CSG_CONE                    183
#define IDI_CSG_CYLINDER                184
#define IDI_CSG_SPHERE                  185
#define IDI_CSGMODE_INTERSECT           186
#define IDI_CSGMODE_SUB                 187
#define IDD_SHAPE3                      187
#define IDI_CSGMODE_UNION               188
#define IDD_SHAPE1                      188
#define IDD_SHAPE2                      189
#define IDD_CSG1                        190
#define IDD_CSG3                        191
#define IDD_CSGMODE                     192
#define IDD_CREATE_MATERIAL             193
#define IDD_CREATE_STENCIL              194
#define IDD_TORUS                       195
#define IDM_BAR_ACTION                  196
#define IDC_PREVIEW_RAYTRACE            1000
#define IDC_PREVIEW_BGIMAGE             1001
#define IDC_BG_LIGHT                    1002
#define IDC_BG_COLOR                    1003
#define IDC_BG_IMAGE                    1004
#define IDC_BG_SKY                      1005
#define IDC_RES_VALID                   1006
#define IDC_XRES                        1007
#define IDC_YRES                        1008
#define IDC_XRES_SPIN                   1009
#define IDC_ACT_NEBULAR                 1010
#define IDC_YRES_SPIN                   1011
#define IDC_SPP                         1012
#define IDC_RAYDEPTH                    1013
#define IDC_ACT_DISTRIBUTED             1014
#define IDC_RAYDEPTH_LEGEND             1015
#define IDC_TFLTR_BOX                   1016
#define IDC_BG_IMAGE_SELECT             1017
#define IDC_TFLTR_GAUSS                 1018
#define IDC_BG_TOP_SELECT               1019
#define IDC_TFLTR_SHUTTER               1020
#define IDC_BG_BOTTOM_SELECT            1021
#define IDC_ACT_MOTION_BLUR             1022
#define IDC_OPEN_GFX                    1023
#define IDC_SPF                         1024
#define IDC_SHADOW_BRIGHTNESS           1025
#define IDC_SMP_REGULAR                 1026
#define IDC_NEB_PREVIEW                 1027
#define IDC_SHADOW_BRIGHTNESS_LEGEND    1028
#define IDC_SMP_RANDOM                  1029
#define IDC_NEB_DISTANCE                1030
#define IDC_SMP_JITTER                  1031
#define IDC_LF_PREVIEW                  1032
#define IDC_SMP_SEMI                    1033
#define IDC_SS4_GREEN_LEGEND            1034
#define IDC_SMP_SEPARATED               1035
#define IDC_SS4_RED_LEGEND              1036
#define IDC_PFLTR_BOX                   1037
#define IDC_SS4_BLUE_LEGEND             1038
#define IDC_PFLTR_GAUSS                 1039
#define IDC_SPP_SPIN                    1040
#define IDC_SCAN_PARA                   1041
#define IDC_SPF_SPIN                    1042
#define IDC_SNAP_TO_GRID                1043
#define IDC_SNAP_TO_ANGLE               1044
#define IDC_STEP_GRID                   1045
#define IDC_STEP_ANGLE                  1046
#define IDC_FULCRUM_X                   1047
#define IDC_FULCRUM_Y                   1048
#define IDC_FULCRUM_Z                   1049
#define IDC_FULCRUM_CLR                 1040
#define IDC_NEW_ITEM_NAME               1051
#define IDC_ITEM_CREATE_LABEL           1052
#define IDC_ACT_LENS_FLARE              1053
#define IDC_LIGHT_LIST                  1054
#define IDC_LF_CHANGE                   1055
#define IDC_LIGHT_NEW                   1056
#define IDC_LF_COLOR                    1057
#define IDC_LIGHT_DELETE                1058
#define IDC_LF_VALUE                    1059
#define IDC_LIGHT_ENABLE                1060
#define IDC_NEB_COLOR                   1061
#define IDC_LIGHT_SOFT                  1062
#define IDC_LIGHT_LDC                   1063
#define IDC_LIGHT_COLOR_CHANGE          1064
#define IDC_SS4_ACTIVE                  1065
#define IDC_LIGHT_COLOR                 1066
#define IDC_SS4_RED                     1067
#define IDC_LIGHT_POS_X                 1068
#define IDC_SS4_GREEN                   1069
#define IDC_LIGHT_POS_Y                 1070
#define IDC_SS4_BLUE                    1071
#define IDC_LIGHT_POS_Z                 1072
#define IDC_HIERARCHY                   1073
#define IDC_LIGHT_DISTR                 1074
#define IDC_LIGHT_DISTANCE              1075
#define IDC_LIGHT_SOFT_SIZE             1076
#define IDC_LIGHT_DIR_X                 1077
#define IDC_LIGHT_DIR_Y                 1078
#define IDC_LIGHT_DIR_Z                 1079
#define IDC_LIGHT_SAMPLE_LABEL          1080
#define IDC_LIGHT_LDC_CONTROL           1081
#define IDC_LIGHT_PREVIEW               1082
#define IDC_PATH_FIRST                  1083
#define IDC_LIGHT_LDC_DIAGRAM           1084
#define IDC_COPYRIGHT                   1085
#define IDC_PATH_PREV                   1086
#define IDC_VERSION                     1087
#define IDC_PATH_SUCC                   1088
#define IDC_CAMERA_LIST                 1089
#define IDC_PATH_LAST                   1090
#define IDC_CAMERA_NEW                  1091
#define IDC_PATH_NEW                    1092
#define IDC_CAMERA_DELETE               1093
#define IDC_PATH_DELETE                 1094
#define IDC_CAMERA_POS_X                1095
#define IDC_PATH_LIST                   1096
#define IDC_CAMERA_POS_Y                1097
#define IDC_PATH_EDIT                   1098
#define IDC_CAMERA_POS_Z                1099
#define IDC_CAMERA_FOCAL_LENGTH         1100
#define IDC_CAMERA_WIDTH                1101
#define IDC_CAMERA_HEIGHT               1102
#define IDC_CAMERA_TYPES                1103
#define IDC_CAMERA_VIEW_X               1104
#define IDC_CAMERA_VIEW_Y               1105
#define IDC_CAMERA_VIEW_Z               1106
#define IDC_CAMERA_ACTIVATION           1107
#define IDC_STEP_MOVE_X                 1108
#define IDC_STEP_MOVE_Y                 1109
#define IDC_STEP_MOVE_Z                 1110
#define IDC_STEP_ROT_X                  1111
#define IDC_STEP_ROT_Y                  1112
#define IDC_STEP_ROT_Z                  1113
#define IDC_OFFSET_X                    1114
#define IDC_OFFSET_Y                    1115
#define IDC_OFFSET_Z                    1116
#define IDC_ROT_X                       1117
#define IDC_ROT_Y                       1118
#define IDC_ROT_Z                       1119
#define IDC_NUM_COPIES                  1120
#define IDC_MOVE_LEFT                   1121
#define IDC_MOVE_UP                     1122
#define IDC_MOVE_DOWN                   1123
#define IDC_MOVE_RIGHT                  1124
#define IDC_CENTER_X                    1125
#define IDC_CENTER_Y                    1126
#define IDC_CENTER_Z                    1127
#define IDC_CENTER_COPYBACK             1128
#define IDC_CENTER_CLEAR                1129
#define IDC_NUM_COPYIES_SPIN            1130
#define IDC_ROT_X_USE                   1131
#define IDC_ROT_Y_USE                   1132
#define IDC_ROT_Z_USE                   1133
#define IDC_OFFSET_X_USE                1134
#define IDC_OFFSET_Y_USE                1135
#define IDC_OFFSET_Z_USE                1136
#define IDC_ROT_LEFT                    1137
#define IDC_ROT_RIGHT                   1138
#define IDC_PREVIEW                     1139
#define IDC_IMAGE                       1140
#define IDC_PREVIEW_IMAGE               1141
#define IDC_UNIT                        1142
#define IDC_PRTDLG_MEASURE              1143
#define IDC_EDIT1                       1144
#define IDC_CUSTOM_MEASURE              1145
#define IDC_PRT_BUFFER                  1146
#define IDC_REFLECTANCE                 1147
#define IDC_X_START                     1148
#define IDC_MEASURE                     1149
#define IDC_X_END                       1150
#define IDC_PRT_BUFFER_SPIN             1151
#define IDC_Y_START                     1152
#define IDC_CAMERA_UNIT                 1153
#define IDC_Y_END                       1154
#define IDC_OBJECTLIST                  1155
#define IDC_CSGMODE_UNION               1156
#define IDC_CSGMODE_INTERSECT           1157
#define IDC_COLOR_AMBIENT               1158
#define IDC_CSGMODE_SUB                 1159
#define IDC_COLOR_DIFFUSE               1160
#define IDC_COLOR_SPECULAR              1161
#define IDC_PREVIEW_MATERIAL            1162
#define IDC_REALLY_CREATE               1163
#define IDC_CHANGE_AMBIENT              1164
#define IDC_CHANGE_DIFFUSE              1165
#define IDC_CHANGE_SPECULAR             1166
#define IDC_REFRACTANCE                 1167
#define IDC_INDEX_OF_REFRACTION         1168
#define IDC_SPEC_EXPONENT               1169
#define IDC_TEXTURE_SELECT              1170
#define IDC_PREVIEW_TEXTURE             1171
#define IDC_TEXTURE                     1172
#define IDC_RELATIVE                    1173
#define IDC_X_START_LEGEND              1174
#define IDC_X_END_LEGEND                1175
#define IDC_Y_START_LEGEND              1176
#define IDC_Y_END_LEGEND                1177
#define IDC_DIRECTION                   1178
#define IDC_POSITION                    1179
#define IDC_BASE_X                      1180
#define IDC_BASE_Y                      1181
#define IDC_BASE_Z                      1182
#define IDC_DIR1_X                      1183
#define IDC_DIR1_Y                      1184
#define IDC_DIR1_Z                      1185
#define IDC_DIR2_X                      1186
#define IDC_DIR2_Y                      1187
#define IDC_DIR2_Z                      1188
#define IDC_DIR3_X                      1189
#define IDC_DIR3_Y                      1190
#define IDC_DIR3_Z                      1191
#define IDC_DIR1_LEN                    1192
#define IDC_DIR2_LEN                    1193
#define IDC_DIR3_LEN                    1194
#define ID_PREF_SAVE                    30005
#define ID_PREF_AUTOSAVE                30006
#define ID_CUST_VIEW                    30026
#define ID_CUST_MAIN                    30029
#define ID_B3_ORIGINAL                  30041
#define ID_B3_WIDTH                     30042
#define ID_B3_HEIGHT                    30043
#define ID_B3_FULL                      30044
#define ID_B3_MORE                      30045
#define ID_B3_LESS                      30046
#define ID_B3_MAGNIFY                   30047
#define ID_B3_UNFILTERED                30048
#define ID_B3_FILTERED                  30049
#define ID_PAGE_SAVE                    31000
#define ID_VIEW_THUMB                   31014
#define ID_PAGE_SAVE_ALL                31015
#define ID_VIEW_PARAM_DEFINE            31029
#define ID_VIEW_PARAM_SET               31030
#define ID_VIEW_PARAM_DELETE            31031
#define ID_SHOW_RES                     31036
#define ID_FRONT                        32771
#define ID_VIEW_TOP                     32772
#define ID_VIEW_BACK                    32774
#define ID_VIEW_LEFT                    32775
#define ID_VIEW_PERSPECTIVE             32778
#define ID_VIEW_FRONT                   32779
#define ID_VIEW_RIGHT                   32780
#define ID_VIEW_ANTIALIAS               32781
#define ID_VIEW_BIGGER                  32782
#define ID_VIEW_SMALLER                 32783
#define ID_VIEW_SELECT                  32784
#define ID_VIEW_ORIGINAL                32787
#define ID_VIEW_MOVE_RIGHT              32788
#define ID_VIEW_MOVE_LEFT               32789
#define ID_VIEW_MOVE_DOWN               32790
#define ID_VIEW_MOVE_UP                 32791
#define ID_VIEW_POP                     32792
#define ID_ACT_SELECT                   32793
#define ID_OBJECT_MOVE                  32794
#define ID_OBJECT_ROTATE                32795
#define ID_OBJECT_SCALE                 32796
#define ID_CAMERA_TURN                  32797
#define ID_CAMERA_ROTATE                32798
#define ID_CAMERA_MOVE                  32799
#define ID_CAMERA_SELECT                32800
#define ID_LIGHT_SELECT                 32801
#define ID_LIGHT_TURN                   32802
#define ID_CAMERA_VIEW                  32803
#define ID_CUST_ACTION                  32804
#define ID_OBJECT_SELECT                32806
#define ID_HIERACHY                     32808
#define ID_RAYTRACE                     32809
#define ID_CUST_DISPLAY                 32810
#define ID_DLG_SCENE                    32813
#define ID_CUST_SCENE                   32815
#define ID_MODELLER_INFO                32816
#define ID_VIEW_TO_FULCRUM              32817
#define ID_IMG_SAVE                     32818
#define ID_CHANGE_TEXTURE_PATH          32819
#define ID_CUST_CAMERA                  32824
#define ID_CUST_LIGHT                   32825
#define ID_LIGHT_NEW                    32826
#define ID_LIGHT_DELETE                 32827
#define ID_LIGHT_PROPERTIES             32828
#define ID_LIGHT_ENABLE                 32829
#define ID_LIGHT_SOFT                   32830
#define ID_CAMERA_NEW                   32831
#define ID_CAMERA_DELETE                32832
#define ID_CAMERA_PROPERTIES            32833
#define ID_LIGHT_LDC                    32834
#define ID_LIGHT_SPOT                   32835
#define ID_CAMERA_ENABLE                32840
#define ID_DEACTIVATE_REST              32845
#define ID_ACTIVATE_ALL                 32846
#define ID_DEACTIVATE_ALL               32847
#define ID_EDIT_PASTE_SUB               32849
#define ID_ALL_DEACTIVATE_REST          32850
#define ID_OBJECT_DELETE                32851
#define ID_OBJECT_NEW                   32852
#define ID_OBJECT_NEW_SUB               32853
#define ID_OBJECT_LOAD                  32857
#define ID_OBJECT_SAVE                  32858
#define ID_OBJECT_REPLACE               32859
#define ID_OBJECT_COPY                  32860
#define ID_DRAWING_PERF                 32861
#define ID_OBJECT_EDIT                  32862
#define ID_OBJECT_RENAME                32863
#define ID_RENAME                       32864
#define ID_PROPERTIES                   32865
#define ID_COORD_X                      32866
#define ID_COORD_Y                      32867
#define ID_COORD_Z                      32868
#define ID_NEB_CHANGE                   32869
#define ID_ACTIVATE                     32870
#define ID_DEACTIVATE                   32871
#define ID_ALL_ACTIVATE                 32872
#define ID_ALL_DEACTIVATE               32873
#define IDS_TEXTURE_FILTER              60000
#define IDS_TOOLBAR_MAINFRAME           60001
#define IDS_TOOLBAR_VIEW                60002
#define IDS_TOOLBAR_ACTION              60003
#define IDS_TOOLBAR_OBJECT              60004
#define IDS_TOOLBAR_DISPLAY             60005
#define IDS_FRAME_RATE                  60006
#define IDS_RAYTRACE_TITLE              60007
#define IDS_RAYDEPTH                    60008
#define IDS_SCENE_NEW                   60009
#define IDS_SHADOW_BRIGHTNESS           60010
#define IDS_TITLE_SCENE                 60011
#define IDS_SS4_RED_LEGEND              60012
#define IDS_SS4_GREEN_LEGEND            60013
#define IDS_SS4_BLUE_LEGEND             60014
#define IDS_SAVE_IMAGE_FILTER           60015
#define IDS_SELECT_TEXTURE_PATH         60016
#define IDS_TOOLBAR_CAMERA              60017
#define IDS_TOOLBAR_LIGHT               60018
#define IDS_DIALOGBAR_FULCRUM           60019
#define IDS_DIALOGBAR_STEP_MOVE         60020
#define IDS_DIALOGBAR_STEP_ROTATE       60021
#define IDS_DOC_READ                    60022
#define IDS_DOC_REORG                   60023
#define IDS_DOC_VERTICES                60024
#define IDS_DOC_PREPARE                 60025
#define IDS_DOC_BOUND                   60026
#define IDS_DIALOGBAR_HIERARCHY         60027
#define IDS_NEW_OBJECT                  60028
#define IDS_ASK_DELETE_OBJECT           60029
#define IDS_OBJECT_FILTER               60030
#define IDS_DIALOGBAR_ACTION            60031
#define IDS_NEW_CAMERA                  60032
#define IDS_NEW_LIGHT                   60033
#define IDS_NAME_EXISTS                 60034
#define IDS_EMPTY_NAME                  60035
#define IDS_ASK_DELETE_LIGHT            60036
#define IDS_PRT_LEGEND                  60037
#define IDS_PRT_MEASURE                 60038
#define IDS_PRT_FILENAME                60039
#define IDS_PRT_VIEWNAME                60040
#define IDS_PRT_UNIT                    60041
#define IDS_PRT_DATE                    60042
#define IDS_UNKNOWN                     60043
#define IDS_SHAPE_AREA                  60044
#define IDS_SHAPE_DISK                  60045
#define IDS_SHAPE_SPHERE                60046
#define IDS_SHAPE_CYLINDER              60047
#define IDS_SHAPE_CONE                  60048
#define IDS_SHAPE_ELLIPSOID             60049
#define IDS_SHAPE_BOX                   60050
#define IDS_SHAPE_TORUS                 60051
#define IDS_SHAPE_BSPLINE_ROT           60052
#define IDS_SHAPE_BSPLINE_AREA          60053
#define IDS_SHAPE_BSPLINE_CYLINDER      60054
#define IDS_SHAPE_BSPLINE_RING          60055
#define IDS_SHAPE_TRIANGLES             60056
#define IDS_CAMERA_UNIT                 60057
#define IDS_CSG_SPHERE                  60058
#define IDS_CSG_CYLINDER                60059
#define IDS_CSG_CONE                    60060
#define IDS_CSG_ELLIPSOID               60061
#define IDS_CSG_BOX                     60062
#define IDS_CSG_TORUS                   60063
#define IDS_CSG_MODE_NONE               60064
#define IDS_CSG_MODE_UNION              60065
#define IDS_CSG_MODE_INTERSECT          60066
#define IDS_CSG_MODE_SUB                60067
#define IDS_BBOX                        60068
#define IDS_ASK_DELETE_SHAPE            60069
#define IDS_STENCIL_START_UNIT          60070
#define IDS_STENCIL_END_UNIT            60071
#define IDS_STENCIL_START_LENGTH        60072
#define IDS_STENCIL_END_LENGTH          60073
#define IDS_STENCIL_START_ANGLE         60074
#define IDS_STENCIL_END_ANGLE           60075

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        197
#define _APS_NEXT_COMMAND_VALUE         32869
#define _APS_NEXT_CONTROL_VALUE         1196
#define _APS_NEXT_SYMED_VALUE           60076
#endif
#endif
